config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:create, :edit, :update] do
    member do
      get :wents, to: "users#reviews"
      get :concerns
    end
  end
  
  resources :shrines do
    collection do
      get :search, to: "shrines#index"
    end
  end
  
  resources :reviews, except: [:index, :show]
  #only: [:create,:destroy,:update]
  resources :concerns, only: [:create,:destroy]
  
end

app/models/shrine.rb
class Shrine < ApplicationRecord
  belongs_to :prefecture
  validates :name, presence: true, length: { maximum: 20 }
  validates :address, presence: true, length: { maximum: 50 },
                      :uniqueness => { :scope => :prefecture_id }
  
  #google maps
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
                      
  has_many :reviews, dependent: :destroy
  has_many :reviews_user, through: :reviews
  has_many :concerns, dependent: :destroy
  has_many :concerns_user, through: :concerns
  has_many :reviews_pictures, through: :reviews, source: :pictures
  
  def self.shrine_search(search)
      Shrine.where(['name LIKE ?', "%#{search}%"])
  end
end

app/controllers/shrines_controller.rb
class ShrinesController < ApplicationController
  before_action :require_user_logged_in, except: [:index]
  
  def index
    @prefecture = Prefecture.where(area: params[:area_id])
    if params[:search].present?
      #Viewのformで取得したパラメータをモデルに渡す
      @shrine = Shrine.shrine_search(params[:search]).order(id: :asc).page(params[:page]).per(10)
      @search = params[:search]
      @count = Shrine.shrine_search(params[:search]).count
    elsif params[:prefecture_id].present?
      @shrine = Shrine.where(prefecture_id: params[:prefecture_id]).order(prefecture_id: :asc).page(params[:page]).per(10)
    else
      @shrine = Shrine.where(prefecture_id: @prefecture.pluck(:id)).order(prefecture_id: :asc).page(params[:page]).per(10)
    end
    
    unless @shrine.present?
      @shrine = Shrine.all.order(prefecture_id: :asc).page(params[:page]).per(10)
      if params[:search].present?
        @nosearch = params[:search]
        @count = 0
      end
    end
  end
  
  def new
    @shrine = Shrine.new
  end
  
  def create
    @shrine = Shrine.new(shrine_params)

    if @shrine.save
      flash[:success] = '神社を登録しました。'
      redirect_to @shrine
    else
      flash.now[:danger] = '神社の登録に失敗しました。'
      render :new
    end
  end
  
  def show
    @shrine = Shrine.find(params[:id])
    @reviews = @shrine.reviews.order(created_at: :desc)
    counts(@shrine)
  end
  
  def edit
    @shrine = Shrine.find(params[:id])
  end
  
  def update
    @shrine = Shrine.find(params[:id])
    
    if @shrine.update(shrine_params)
      flash[:success] = '神社情報を編集しました。'
      redirect_to @shrine
    else
      flash.now[:danger] = '神社情報の編集に失敗しました。'
      render :edit
    end
  end

  def destroy
    #本当に管理userか入れる
    @shrine = Shrine.find(params[:id])
    @shrine.destroy
    flash[:success] = '神社を削除しました。'
    redirect_to shrines_url(fallback_location: root_path)
  end
  
  private

  def shrine_params
    params.require(:shrine).permit(:name, :address, :prefecture_id)
  end
end

app/views/shrines/_prefecture.html.erb
<% @prefecture.each do |prefecture| %>
<%= prefecture.name %>
<% end %>

app/views/shrines/_searchnav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">北海道</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">東北</a>
        <%= render "shrines/prefecture", prefecture: @prefecture %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
  </div>
</nav>

app/views/shrines/_shrine_form.html.erb
<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @shrine, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :name, '神社名' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :prefecture_id, '都道府県' %>
        <%= f.collection_select :prefecture_id, Prefecture.all, :id, :name, {prompt: "都道府県を選択してください"}, {class: 'form-control'} %>
      </div>

      <div class="form-group">
        <%= f.label :address, 'その他住所' %>
        <%= f.text_field :address, class: 'form-control' %>
      </div>

      <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/shrines/edit.html.erb
<div class="text-center">
  <h1>神社情報の編集</h1>
</div>
<%= render "shrine_form" %>

app/views/shrines/index.html.erb
<div class=example>
<%= image_tag "/assets/中尊寺.jpg", alt: "神社巡り" %>
</div>
<nav class="navbar navbar-expand navbar-dark">
<div class="container">

<ul class="navbar-nav">
  <li class="nav-item"><%= link_to "北海道地方", shrines_path(area_id: "1"), class:"nav-link" %></li>
  <li class="nav-item"><%= link_to "東北地方", shrines_path(area_id: "2"), class:"nav-link" %></li>
  <li class="nav-item"><%= link_to "関東地方", shrines_path(area_id: "3"), class:"nav-link" %></li>
  <li class="nav-item"><%= link_to "中部地方", shrines_path(area_id: "4"), class:"nav-link" %></li>
  <li class="nav-item"><%= link_to "近畿地方", shrines_path(area_id: "5"), class:"nav-link" %></li>
  <li class="nav-item"><%= link_to "中国地方", shrines_path(area_id: "6"), class:"nav-link" %></li>
  <li class="nav-item"><%= link_to "四国地方", shrines_path(area_id: "7"), class:"nav-link" %></li>
  <li class="nav-item"><%= link_to "九州地方", shrines_path(area_id: "8"), class:"nav-link" %></li>
</ul>
</div>
</nav>
<nav class="navbar navbar-expand navbar-dark">
<ul class="navbar-nav">
  <% @prefecture.each do |prefecture| %>
  <li class="nav-item"><%= link_to prefecture.name, shrines_path(prefecture_id: prefecture.id, area_id: prefecture.area), class:"nav-link" %></li>
  <% end %>
</ul>
</nav>

<h2>神社一覧</h2>
<% if @search %>
<h3>"<%= @search %>"の検索結果(<%= @count %>件)</h3>
  <% if @nosearch %>
  <h3>"<%= @nosearch %>"はヒットしませんでした。</h3>
  <% end %>
<% end %>
<div class="row">
<% @shrine.each do |shrine| %>
  <div class="col-md-6">
　  <div class="card mb-3" style="height: 200px">
　    <div class="row">
　    <div class="col-5">
  　     <h5>
        <%= link_to shrine.name, shrine_path(shrine) %>
        (<%= shrine.prefecture.name %>)
        </h5>
        <% if shrine.reviews.present? %>
        <%= render "layouts/star" ,result: shrine.reviews.average(:evaluation).round(1) %>
        <h6>
        レビュー<%= shrine.reviews.count %>
        </h6>
        <% end %>
      </div>
      <div class="col-6">
      <div class="card-body text-center">
        <% if shrine.reviews_pictures.present? %>
        <%= image_tag shrine.reviews_pictures.first.image.url, alt: "image",style: "max-height: 140px" %>
        <% else %>
        <%= image_tag "/assets/default.png", alt: "image", style: "max-height: 140px" %>
        <% end %>
      </div>
      </div>
      </div>
    </div>
  </div>
<% end %>
</div>
<%= paginate @shrine %>

app/views/shrines/new.html.erb
<div class="text-center">
  <h1>神社登録</h1>
    <div style="color: #ff0000;">
　    <h6>
　    ※一度登録した神社は編集・削除ができません。<br>
　    ※登録済みの神社は登録できません。<br>
　    ※神社名、住所は省略せずに正しく入力してください。
　    </h6>
　  </div>
</div>
<%= render "shrine_form" %>

app/views/shrines/show.html.erb
<div class="row">
  <div class="col-md-4">
<h3><%= @shrine.name %></h3>
<h6>住所:
  <%= @shrine.prefecture.name %>
  <%= @shrine.address %>
</h6>

<% if current_user.admin? %>
<%= link_to "神社情報の編集", edit_shrine_path %><br>
<%= link_to "神社を削除する", @shrine, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>
<% end %>

<ul class="nav">
  <% if @shrine.reviews.present? %>
  <li>
    <%= render "layouts/star" ,result: @shrine.reviews.average(:evaluation).round(1) %>
  </li>
  <% end %>
  <li>
    <%= render 'reviews/review_button', shrine: @shrine %>
  </li>
  <li>
    <h5><%= @shrine.reviews.count %></h5>
  </li>
  <li>
    <%= render 'concerns/concern_button', shrine: @shrine %>
  </li>
  <li>
    <h5><%= @shrine.concerns.count %></h5>
  </li>
</ul>
  </div>

<script>
  function initMap() {
//latitude,longitudeから位置を特定
    var test ={lat: <%= @shrine.latitude %>, lng: <%= @shrine.longitude %>};
    var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 15, 
              center: test
              });
    var transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);

    var contentString = '住所：<%= @shrine.address %>';
    var infowindow = new google.maps.InfoWindow({
      content: contentString
    });

//Map上の指定した位置にピンを挿して表示する
    var marker = new google.maps.Marker({
                  position:test,
                  map: map,
                  title: contentString
                 });

     marker.addListener('click', function() {
       infowindow.open(map, marker);
     });
  }
</script>

<!--以下の記述の中にあるYOUR_API_KEYには取得したご自身のAPIキーを記述-->
<script async defer src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap"></script>
<!--表示するmapのcssです。ご自身でカスタマイズしてください。高さが設定されていないと表示されないことがある-->
<!--<style type="text/css">
  #map {
    height: 200px;
    width: 100%;
  }
</style>-->

  <div class="col-md-8">
    <div id="map" style="height: 200px; width: 100%;"></div>
  </div>
</div>
    
<h3>レビュー<%= @shrine.reviews.count %></h3>

<%= render "reviews/index" %>