config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:create, :edit, :update] do
    member do
      get :wents, to: "users#reviews"
      get :concerns
    end
  end
  
  resources :shrines do
    collection do
      get :search, to: "shrines#index"
    end
  end
  
  resources :reviews, except: [:index, :show]
  #only: [:create,:destroy,:update]
  resources :concerns, only: [:create,:destroy]
  
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 20 },
                   uniqueness: true #重複していないか検証
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false } #重複していないか検証、大文字小文字区別
  mount_uploader :user_image, ImageUploader
  
  has_secure_password
  
  has_many :reviews
  has_many :reviews_shrine, through: :reviews, source: :shrine
  has_many :concerns
  has_many :concerns_shrine, through: :concerns, source: :shrine
  has_many :reviews_pictures, through: :reviews, source: :pictures
  #has_many :reviews_pictures, through: :reviews_shrine, source: :pictures
  
  def review?(shrine)
    self.reviews_shrine.include?(shrine)
  end
  
  def concern(shrine)
      self.concerns.find_or_create_by(shrine_id: shrine.id)
  end
  
  def unconcern(shrine)
    concern = self.concerns.find_by(shrine_id: shrine.id)
    concern.destroy if concern
  end
  
  def concern?(shrine)
    self.concerns_shrine.include?(shrine)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to login_path
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def edit
    @user = User.find(params[:id])
    unless current_user == @user
      redirect_to root_url
    end
  end
  
  def update
    @user = User.find(params[:id])
    
    if current_user == @user
    
    if @user.update(user_params)
      flash[:success] = 'ユーザ情報を編集しました。'
      redirect_to wents_user_path(@user)
    else
      flash.now[:danger] = 'ユーザ情報の編集に失敗しました。'
      render :edit
    end
    
    else redirect_to login_url
    end
  end
  
  def reviews
    @user = User.find(params[:id])
    @reviews = @user.reviews.order(created_at: :desc).page(params[:page])
    counts(@user)
    render "users/show_wents"
  end
  
  def concerns
    @user = User.find(params[:id])
    @reviews = @user.concerns.order(created_at: :desc).page(params[:page])
    counts(@user)
    render "users/show_concerns"
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :user_image, :remove_user_image)
  end
end

app/views/users/_shrine.html.erb
<div class="text-center">
<div class="row">
  <% @reviews.each do |review| %>
  
  <div class="col-md-4">
  <div class="card">
    <div class="card-img-top">
    <% if review.shrine.reviews_pictures.present? %>
    <%= image_tag review.shrine.reviews_pictures.first.image.url, alt:"image" %>
    <% else %>
    <%= image_tag "/assets/default.png", alt: "image" %>
    <% end %>
    </div>
  <div class="card-body">
    <h5 class="card-title"><%= link_to review.shrine.name, shrine_path(review.shrine.id) %></h5>
      <table class="table">
        <tr>
          <td>◉</td>
          <td>♡</td>
          <td>☆</td>
        </tr>
      <tbody>
        <tr>
          <td><%= review.shrine.reviews.count %></td>
          <td><%= review.shrine.concerns.count %></td>
          <% if review.shrine.reviews.present? %>
          <td><%= review.shrine.reviews.average(:evaluation).round(1) %></td>
          <% else %>
          <td>0</td>
          <% end %>
        </tr>
      </tbody>
      </table>
  </div>
  </div>
 
  </div>
  <% end %>
</div>
</div>

app/views/users/edit.html.erb
<div class="text-center">
  <h1>ユーザー情報の編集</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :name, 'ユーザー名' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <% if @user.user_image? %>
        <%= image_tag @user.user_image.url, alt:"image" %><br>
        <label>
        <%= f.check_box :remove_user_image, class: 'form-control'%>
        画像を削除
        </label>
        <% end %>
      </div>
        
      <div class="form-group">
          <%= f.file_field :user_image, accept: "image/jpeg,image/jpg,image/png", class: "btn btn-outline-secondary rounded-pill" %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, '新しいパスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, '新しいパスワード(確認用)' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit '編集する', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1>新規登録</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :name, 'ユーザー名' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード(確認用)' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show_concerns.html.erb
<div class="text-center">
  <h2>マイページ</h2>
  <div class="offset-md-4 col-md-4">
    <div class="card">
      <div class="card-title">
        <h3><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <%= image_tag @user.user_image.url, alt:"image",style: "max-height: 200px" %>
      </div>
        <%= link_to "ユーザー情報の編集", edit_user_path(@user) %>
    </div>
  </div>
  <div class="offset-md-1 col-md-10">
    <ul class="nav nav-fill">
      <li class="nav-item">
        <%= link_to "行った◉", wents_user_path(current_user), class: 'btn btn-light btn-block' %> 
        <%= @count_user_reviews %>
      </li>
      <li class="nav-item">
        <%= link_to "気になる♡", concerns_user_path(current_user), class: 'btn btn-warning btn-block' %> 
        <%= @count_user_concerns %>
      </li>
    </ul>
  </div>
</div>
<%= render "shrine" %>

app/views/users/show_wents.html.erb
<div class="text-center">
  <h2>マイページ</h2>
  <div class="offset-md-4 col-md-4">
    <div class="card">
      <div class="card-title">
        <h3><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <%= image_tag @user.user_image.url, alt:"image",style: "max-height: 200px" %>
      </div>
        <%= link_to "ユーザー情報の編集", edit_user_path(@user) %>
    </div>
  </div>
  <div class="offset-md-1 col-md-10">
    <ul class="nav nav-fill">
      <li class="nav-item">
        <%= link_to "行った◉", wents_user_path(current_user), class: 'btn btn-warning btn-block' %> 
        <%= @count_user_reviews %>
      </li>
      <li class="nav-item">
        <%= link_to "気になる♡", concerns_user_path(current_user), class: 'btn btn-light btn-block' %> 
        <%= @count_user_concerns %>
      </li>
    </ul>
  </div>
</div>
<%= render "shrine" %>