config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:create, :edit, :update] do
    member do
      get :wents, to: "users#reviews"
      get :concerns
    end
  end
  
  resources :shrines do
    collection do
      get :search, to: "shrines#index"
    end
  end
  
  resources :reviews, except: [:index, :show]
  #only: [:create,:destroy,:update]
  resources :concerns, only: [:create,:destroy]
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_user_logged_in
  
  def new
    @review = Review.new
    @user = current_user
    @shrine = Shrine.find(params[:shrine_id])
    #3.times { @review.pictures.build }
    @review.pictures.build
  end
  
  def edit
    @user = current_user
    @review = Review.find(params[:review_id])
    @shrine = Shrine.find(@review.shrine.id)
    unless @review.pictures.present?
      @review.pictures.build
    end
    unless @review.user == current_user
      redirect_to root_url
    end
    #t=3-@lesson.lesson_images.size.to_i(複数投稿)
    #t.times{@lesson.lesson_images.build}
    #3.times { @review.pictures.build } 
    #end
  end
  
  def create
    @review = Review.new(review_params)
    shrine = @review.shrine
    if @review.save
      current_user.concern?(shrine) if current_user.unconcern(shrine)
    flash[:success] = 'レビューしました'
    redirect_to shrine_url(@review.shrine.id)
    
    else
      flash.now[:danger] = 'レビューに失敗しました。'
      @user = current_user
      @shrine = shrine
      unless @review.pictures.present?
      @review.pictures.build
      end
      render :new
    end
  end
  
  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    flash[:success] = 'レビューを削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
  def update
    @review = Review.find(params[:id])
    
    if @review.update(review_params)
      flash[:success] = 'レビューを編集しました。'
      redirect_to shrine_url(@review.shrine.id)
      
    else
      flash.now[:danger] = 'レビューの編集に失敗しました。'
      render :edit
    end
  end

  private

  def review_params
    params.require(:review).permit(:evaluation, :comment, :user_id, :shrine_id, pictures_attributes: [:id, :image, :image_cache, :_destroy])
  end
end

app/views/reviews/_index.html.erb
<% @reviews.each do |review| %>

<div class="card">
  <div class="card-body">
    <ul class="nav">
    <li><h5 class="card-title"><%= review.user.name %></h5></li>
    <li>
    <% if current_user==review.user %>
    <%= link_to "レビューを編集する", edit_review_path(review_id: review.id) %>
    <% end %>
    </li>
    <% if current_user.admin? %>
    <li>
    <%= link_to "レビューを削除する", review, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>
    </li>
    <% end %>
    </ul>
    
<%= render 'layouts/star', result: review.evaluation.to_f %>
    
  <div class="row">
    <div class="col-4">
      <div class="review-image">
      <% review.pictures.each do |picture| %>
      <%= image_tag picture.image.to_s, alt:"image" %>
      <% end %>
      </div>
    </div>
  </div>
    
  <% if review.comment? %>
  <p>コメント</p>
  <%= review.comment %>
  <% end %>
  </div>
</div>
<% end %>

app/views/reviews/_review_button.html.erb
<% if current_user.review?(shrine) %>
  <%= form_with(model: current_user.reviews.find_by(shrine_id: shrine.id), local: true, method: :delete) do |f| %>
    
    <%= f.submit '行った◉', class: 'btn btn-warning', data: { confirm: 'レビューも削除されます。本当に削除してよろしいですか？' }%>
  <% end %>
<% else %>
  <%= link_to "行った◉", new_review_path(shrine_id: shrine.id) , class: 'btn btn-light'%>
<% end %>

app/views/reviews/edit.html.erb
<div class="text-center">
  <h1>神社レビュー</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @review, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :evaluation, '星(必須)' %>
        <%= f.select :evaluation, ["1","2","3","4","5"], {prompt: "選択してください"}, {class: 'form-control'} %>
      </div>

      <div class="form-group">
        <%= f.label :comment, 'コメント(任意)' %>
        <%= f.text_area :comment, class: 'form-control', size: "100×50" %>
      </div>
      
      <%= f.hidden_field :user_id, value: @user.id %>
      <%= f.hidden_field :shrine_id, value: @shrine.id %>
      
      <%= f.fields_for :pictures do |picture| %>
      <div class="form-group">
        <% if @review.pictures.exists? %>
        <label>
        <%= picture.check_box :_destroy, class: 'form-control'%>
        画像を削除
        </label>
        <% end %>
        
          <%= picture.file_field :image, accept: "image/jpeg,image/jpg,image/png", class: "btn btn-outline-secondary rounded-pill" %>
          <%= f.hidden_field :image_cache %>
        (任意)
      </div>
      <% end %>

      <%= f.submit 'レビューする', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="text-center">
  <h1>神社レビュー</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @review, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :evaluation, '星(必須)' %>
        <%= f.select :evaluation, ["1","2","3","4","5"], {prompt: "選択してください"}, {class: 'form-control'} %>
      </div>

      <div class="form-group">
        <%= f.label :comment, 'コメント(任意)' %>
        <%= f.text_area :comment, class: 'form-control', cols: "50" %>
      </div>
      
      <%= f.hidden_field :user_id, value: @user.id %>
      <%= f.hidden_field :shrine_id, value: @shrine.id %>
      
      
      <%= f.fields_for :pictures do |picture| %>
      <div class="form-group">
          <%= picture.file_field :image, accept: "image/jpeg,image/jpg,image/png", class: "btn btn-outline-secondary rounded-pill" %>
          <%= f.hidden_field :image_cache %>
        (任意)
      </div>
      <% end %>

      <%= f.submit 'レビューする', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>