config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:create, :edit, :update] do
    member do
      get :wents, to: "users#reviews"
      get :concerns
    end
  end
  
  resources :shrines do
    collection do
      get :search, to: "shrines#index"
    end
  end
  
  resources :reviews, except: [:index, :show]
  #only: [:create,:destroy,:update]
  resources :concerns, only: [:create,:destroy]
  
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-md navbar-dark">
    <div class="container">
      
    <a class="navbar-brand" href="/">神社巡り</a>
    <%= form_tag(search_shrines_path,:method => 'get') do %>
      <%= text_field_tag :search %>
      <%= submit_tag 'Search', :name => nil %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
          <li class="nav-item"><%= link_to "トップページ", root_path, class:"nav-link" %></li>
          <li class="nav-item"><%= link_to "神社検索", shrines_path, class:"nav-link" %></li>
        <% if logged_in? %>
          <li class="nav-item"><%= link_to "神社登録", new_shrine_path, class:"nav-link" %></li>
          <li class="nav-item"><%= link_to "マイページ", wents_user_path(current_user), class:"nav-link" %></li>
          <li class="nav-item"><%= link_to "ログアウト", logout_path, method: :delete, class:"nav-link" %></li>
        <% else %>
          <li class="nav-item"><%= link_to "新規登録", signup_path, class:"nav-link" %></li>
          <li class="nav-item"><%= link_to "ログイン", login_path, class:"nav-link" %></li>
        <% end %>
      </ul>
    </div>
    </div>
  </nav>
</header>

app/views/layouts/_star.html.erb
<% if result >= 4.5 %>
<div class="fa-yellow" style="display: inline-block">
  <i class="fas fa-star"></i>
  <i class="fas fa-star"></i>
  <i class="fas fa-star"></i>
  <i class="fas fa-star"></i>
  <i class="fas fa-star"></i>
</div>
<%= result %>

<% elsif result >= 3.5 %>
<div class="fa-yellow" style="display: inline-block">
  <i class="fas fa-star"></i>
  <i class="fas fa-star"></i>
  <i class="fas fa-star"></i>
  <i class="fas fa-star"></i>
  <i class="far fa-star"></i>
</div>
<%= result %>

<% elsif result >= 2.5 %>
<div class="fa-yellow" style="display: inline-block">
  <i class="fas fa-star"></i>
  <i class="fas fa-star"></i>
  <i class="fas fa-star"></i>
  <i class="far fa-star"></i>
  <i class="far fa-star"></i>
</div>
<%= result %>

<% elsif result >= 1.5 %>
<div class="fa-yellow" style="display: inline-block">
  <i class="fas fa-star"></i>
  <i class="fas fa-star"></i>
  <i class="far fa-star"></i>
  <i class="far fa-star"></i>
  <i class="far fa-star"></i>
</div>
<%= result %>

<% elsif result >= 0 %>
<div class="fa-yellow" style="display: inline-block">
  <i class="fas fa-star"></i>
  <i class="far fa-star"></i>
  <i class="far fa-star"></i>
  <i class="far fa-star"></i>
  <i class="far fa-star"></i>
</div>
<%= result %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Shrines</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <div class="container">
      <%= render "layouts/navbar" %>
      <%= render 'layouts/flash_messages' %>
      
      <%= yield %>
    </div>
  </body>
</html>